
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umc_jpa
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
      hibernate:
        ddl-auto: create
      show_sql: true
      properties:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000